### PR TITLE
req/dump: Add print function for custom printer.

### PR DESCRIPTION
**Pull request by atlas-comstock**

### CODE REVIEW

**Comment by YongHaoWu** [comment]
@imroc Can have more discussion on this.

**Comment by imroc** [comment]
xref: https://github.com/imroc/req/issues/42

You can get the dump by calling `resp.Dump()` and log it anywhere you want.

**Comment by YongHaoWu** [comment]
@imroc As u have integrated `debug` function and used `fmt.Println` in the library, I think use a custom print function is better than I dump the request and resp by myself.

**Comment by YongHaoWu** [comment]
@imroc Any response?

**Pull request closed without merging**
